<a href="https://colab.research.google.com/github/019Vipin/Numpy-and-Pandas-tutorials/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy tutorials


Advantages of Numpy Arrays:

1.Allows several Mathematical Operations
2.Faster operations

In [ ]:
import numpy as np
import pandas as pd

List vs numpy - time taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0005561960000002308


time taken by numpy

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0007675860000002643


Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.45866332 0.13868901 0.71022856 0.00986275]
 [0.85445257 0.54484063 0.85070271 0.42396639]
 [0.33201477 0.53824656 0.81359642 0.52515288]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[55 50 86 97 44]
 [43 16 59 81 97]
 [41 15 92 14 55]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[89 10 17 58 75]
 [48 41 57 17 80]
 [26 23 67 73 37]
 [81 87 58 80 54]
 [74 19 32 81 11]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[6 4 0]
 [2 7 0]
 [0 7 9]]
[[19 12 19]
 [17 17 13]
 [13 14 15]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[25 16 19]
 [19 24 13]
 [13 21 24]]
[[-13  -8 -19]
 [-15 -10 -13]
 [-13  -7  -6]]
[[114  48   0]
 [ 34 119   0]
 [  0  98 135]]
[[0.31578947 0.33333333 0.        ]
 [0.11764706 0.41176471 0.        ]
 [0.         0.5        0.6       ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[3 0 2]
 [4 3 4]
 [9 3 1]]
[[11 17 17]
 [14 10 11]
 [16 11 11]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 17 19]
 [18 13 15]
 [25 14 12]]
[[ -8 -17 -15]
 [-10  -7  -7]
 [ -7  -8 -10]]
[[ 33   0  34]
 [ 56  30  44]
 [144  33  11]]
[[0.27272727 0.         0.11764706]
 [0.28571429 0.3        0.36363636]
 [0.5625     0.27272727 0.09090909]]


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 9 2]
 [6 2 6]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 6]
 [9 2]
 [2 6]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 8 7]
 [0 1 3]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 0]
 [8 1]
 [7 3]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 3 5]
 [6 4 4]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 3]
 [5 6]
 [4 4]]
(3, 2)


# pandas tutorials


Pandas Library:

Useful for Data Processing & Analysis

Pandas Data Frame:

Pandas DataFrame is two-dimensional tabular data structure with labeled axes (rows and columns).

In [ ]:
# importing the pandas library
import pandas as pd
import numpy as np

Creaating a Pandas DataFrame

In [ ]:
from sklearn.datasets import fetch_california_housing

housing_dataset = fetch_california_housing(as_frame=True)
X = housing_dataset.data
y = housing_dataset.target


In [ ]:
print(housing_dataset)

{'data':        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -1

In [ ]:
# pandas DataFrame
import pandas as pd
housing_df = pd.DataFrame(housing_dataset.data, columns = housing_dataset.feature_names)


In [ ]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
housing_df.shape

(20640, 8)

In [ ]:
type(housing_df)

pandas.core.frame.DataFrame


Importing the data from a CSV file to a pandas DataFrame

In [ ]:
diabetes_df = pd.read_csv('/content/diabetes.csv')

In [ ]:
type(diabetes_df)

pandas.core.frame.DataFrame

In [ ]:
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
diabetes_df.shape

(768, 9)

Loading the data from a excel file to a Pandas DataFrame:

pd.read_excel('file path')

Exporting a DataFrame to a csv file

In [ ]:
housing_df.to_csv('housing.csv')

Exporting the Pandas DataFrame to an excel File:

df.to_excel('filename')

In [ ]:
# creating a DatFrame with random values
import numpy as np
random_df = pd.DataFrame(np.random.rand(20,10))

In [ ]:
random_df.head()

0         1         2         3         4         5         6  \
0  0.600442  0.663714  0.980450  0.692931  0.732547  0.959250  0.595523   
1  0.754072  0.290419  0.727531  0.372169  0.448640  0.564748  0.242048   
2  0.388584  0.949255  0.143265  0.588294  0.196799  0.931678  0.620974   
3  0.119960  0.160420  0.990212  0.342040  0.855680  0.806238  0.802301   
4  0.113569  0.808688  0.555381  0.229033  0.077060  0.282962  0.582499   

          7         8         9  
0  0.162284  0.938591  0.518016  
1  0.970659  0.195065  0.554363  
2  0.671602  0.573010  0.987983  
3  0.912886  0.982371  0.744641  
4  0.486800  0.009281  0.780056

In [ ]:
random_df.shape

(20, 10)

Inspecting a DataFrame

In [ ]:
#finding the number of rows & columns
housing_df.shape

(20640, 8)

In [ ]:
# first 5 rows in a DataFrame
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
# last 5 rows of the DataFrame
housing_df.tail()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24

In [ ]:
# informations about the DataFrame
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


In [ ]:
# finding the number of missing values
housing_df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [ ]:
# diabetes dataframe
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
# counting the values based on the labels
diabetes_df.value_counts('Outcome')

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
# group the values based on the mean
diabetes_df.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

Statistical Measures

In [ ]:
# count or number of values
housing_df.count()

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
dtype: int64

In [ ]:
# mean value - column wise
housing_df.mean()

MedInc           3.870671
HouseAge        28.639486
AveRooms         5.429000
AveBedrms        1.096675
Population    1425.476744
AveOccup         3.070655
Latitude        35.631861
Longitude     -119.569704
dtype: float64

In [ ]:
# standard deviation - column wise
housing_df.std()

MedInc           1.899822
HouseAge        12.585558
AveRooms         2.474173
AveBedrms        0.473911
Population    1132.462122
AveOccup        10.386050
Latitude         2.135952
Longitude        2.003532
dtype: float64

In [ ]:
# minimum value
housing_df.min()

MedInc          0.499900
HouseAge        1.000000
AveRooms        0.846154
AveBedrms       0.333333
Population      3.000000
AveOccup        0.692308
Latitude       32.540000
Longitude    -124.350000
dtype: float64

In [ ]:
# maximum value
housing_df.max()

MedInc           15.000100
HouseAge         52.000000
AveRooms        141.909091
AveBedrms        34.066667
Population    35682.000000
AveOccup       1243.333333
Latitude         41.950000
Longitude      -114.310000
dtype: float64

In [ ]:
# all the statistical measures about the dataframe
housing_df.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000

Manipulating a DataFrame

In [ ]:
# adding a column to a dataframe
housing_df['Price'] = housing_dataset.target

In [ ]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  Price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [ ]:
# removing a row
housing_df.drop(index=0, axis=0)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
5      4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  Price  
1        -122.22  3.585  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
5        -122.25  2.697  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20639 rows x 9 columns]

In [ ]:
# drop a column
housing_df.drop(columns='Latitude', axis=1)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Longitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556    -122.23   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842    -122.22   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260    -122.24   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945    -122.25   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467    -122.25   
...       ...       ...       ...        ...         ...       ...        ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606    -121.09   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807    -121.21   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635    -121.22   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209    -121.32   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981    -121.24   

       Price  
0      4.526  
1      3.585  
2      3.521  
3      3.413  
4      3.422  
...      ...  
20635  0.781  
20636  0.771  
20637  0.923  
20638  0.847  
20639  0.894  

[20640 rows x 8 columns]

In [ ]:
# locating a row using the index value
housing_df.iloc[2]

MedInc          7.257400
HouseAge       52.000000
AveRooms        8.288136
AveBedrms       1.073446
Population    496.000000
AveOccup        2.802260
Latitude       37.850000
Longitude    -122.240000
Price           3.521000
Name: 2, dtype: float64

In [ ]:
# locating a particular column
print(housing_df.iloc[:,0])  # first column
print(housing_df.iloc[:,1])  # second column
print(housing_df.iloc[:,2])  # third column
print(housing_df.iloc[:,-1]) # last column

0        8.3252
1        8.3014
2        7.2574
3        5.6431
4        3.8462
          ...  
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: MedInc, Length: 20640, dtype: float64
0        41.0
1        21.0
2        52.0
3        52.0
4        52.0
         ... 
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: HouseAge, Length: 20640, dtype: float64
0        6.984127
1        6.238137
2        8.288136
3        5.817352
4        6.281853
           ...   
20635    5.045455
20636    6.114035
20637    5.205543
20638    5.329513
20639    5.254717
Name: AveRooms, Length: 20640, dtype: float64
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Price, Length: 20640, dtype: float64


Correlation:

 1.Positive Correlation
 2.Negative Correlation

In [ ]:
housing_df.corr()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.119034  0.326895  -0.062040    0.004834  0.018766   
HouseAge   -0.119034  1.000000 -0.153277  -0.077747   -0.296244  0.013191   
AveRooms    0.326895 -0.153277  1.000000   0.847621   -0.072213 -0.004852   
AveBedrms  -0.062040 -0.077747  0.847621   1.000000   -0.066197 -0.006181   
Population  0.004834 -0.296244 -0.072213  -0.066197    1.000000  0.069863   
AveOccup    0.018766  0.013191 -0.004852  -0.006181    0.069863  1.000000   
Latitude   -0.079809  0.011173  0.106389   0.069721   -0.108785  0.002366   
Longitude  -0.015176 -0.108197 -0.027540   0.013344    0.099773  0.002476   
Price       0.688075  0.105623  0.151948  -0.046701   -0.024650 -0.023737   

            Latitude  Longitude     Price  
MedInc     -0.079809  -0.015176  0.688075  
HouseAge    0.011173  -0.108197  0.105623  
AveRooms    0.106389  -0.027540  0.151948  
AveBedrms   0.069721   0.013344 -0.046701  
Population -0.108785   0.099773 -0.024650  
AveOccup    0.002366   0.002476 -0.023737  
Latitude    1.000000  -0.924664 -0.144160  
Longitude  -0.924664   1.000000 -0.045967  
Price      -0.144160  -0.045967  1.000000