<a href="https://colab.research.google.com/github/019Vipin/Numpy-and-Pandas-tutorials/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy tutorials


Advantages of Numpy Arrays:

1.Allows several Mathematical Operations
2.Faster operations

In [ ]:
import numpy as np
import pandas as pd

List vs numpy - time taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0005561960000002308


time taken by numpy

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0007675860000002643


Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.45866332 0.13868901 0.71022856 0.00986275]
 [0.85445257 0.54484063 0.85070271 0.42396639]
 [0.33201477 0.53824656 0.81359642 0.52515288]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[55 50 86 97 44]
 [43 16 59 81 97]
 [41 15 92 14 55]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[89 10 17 58 75]
 [48 41 57 17 80]
 [26 23 67 73 37]
 [81 87 58 80 54]
 [74 19 32 81 11]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[6 4 0]
 [2 7 0]
 [0 7 9]]
[[19 12 19]
 [17 17 13]
 [13 14 15]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[25 16 19]
 [19 24 13]
 [13 21 24]]
[[-13  -8 -19]
 [-15 -10 -13]
 [-13  -7  -6]]
[[114  48   0]
 [ 34 119   0]
 [  0  98 135]]
[[0.31578947 0.33333333 0.        ]
 [0.11764706 0.41176471 0.        ]
 [0.         0.5        0.6       ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[3 0 2]
 [4 3 4]
 [9 3 1]]
[[11 17 17]
 [14 10 11]
 [16 11 11]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 17 19]
 [18 13 15]
 [25 14 12]]
[[ -8 -17 -15]
 [-10  -7  -7]
 [ -7  -8 -10]]
[[ 33   0  34]
 [ 56  30  44]
 [144  33  11]]
[[0.27272727 0.         0.11764706]
 [0.28571429 0.3        0.36363636]
 [0.5625     0.27272727 0.09090909]]


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 9 2]
 [6 2 6]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 6]
 [9 2]
 [2 6]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 8 7]
 [0 1 3]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 0]
 [8 1]
 [7 3]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 3 5]
 [6 4 4]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 3]
 [5 6]
 [4 4]]
(3, 2)
